package com.jw.util;

/**
 * @author mioko
 */
public interface CodeUtil {
    String LOGIN_SUCCESS = "LOGIN SUCCESS";
    String LOGIN_FAILED = "LOGIN FAILED";
    String FORBIDDEN = "403 FORBIDDEN";
    String USER_DISABLED = "USER DISABLED";
    String UPDATE_SUCCESS="UPDATE SUCCESS";
    String UPDATE_FAILED="UPDATE FAILED";
    String ADD_SUCCESS="ADD SUCCESS";
    String ADD_FAILED="ADD FAILED";
    String DELETE_SUCCESS="DELETE SUCCESS";
    String DELETE_FAILED="DELETE FAILED";
    String UNAUTHORIZED="UNAUTHORIZED";
    String EXIST_ROLE_OF_USER="EXIST ROLE OF USER";
}
